const OPENCLAW_EXTENSION_SLUG_TO_PACKAGE = {
  acpx: "@openclaw/acpx",
  "active-memory": "@openclaw/active-memory",
  alibaba: "@openclaw/alibaba-provider",
  "alibaba-provider": "@openclaw/alibaba-provider",
  "amazon-bedrock": "@openclaw/amazon-bedrock-provider",
  "amazon-bedrock-mantle": "@openclaw/amazon-bedrock-mantle-provider",
  "amazon-bedrock-mantle-provider": "@openclaw/amazon-bedrock-mantle-provider",
  "amazon-bedrock-provider": "@openclaw/amazon-bedrock-provider",
  anthropic: "@openclaw/anthropic-provider",
  "anthropic-provider": "@openclaw/anthropic-provider",
  "anthropic-vertex": "@openclaw/anthropic-vertex-provider",
  "anthropic-vertex-provider": "@openclaw/anthropic-vertex-provider",
  arcee: "@openclaw/arcee-provider",
  "arcee-provider": "@openclaw/arcee-provider",
  "azure-speech": "@openclaw/azure-speech",
  bluebubbles: "@openclaw/bluebubbles",
  bonjour: "@openclaw/bonjour",
  brave: "@openclaw/brave-plugin",
  "brave-plugin": "@openclaw/brave-plugin",
  browser: "@openclaw/browser-plugin",
  "browser-plugin": "@openclaw/browser-plugin",
  byteplus: "@openclaw/byteplus-provider",
  "byteplus-provider": "@openclaw/byteplus-provider",
  cerebras: "@openclaw/cerebras-provider",
  "cerebras-provider": "@openclaw/cerebras-provider",
  chutes: "@openclaw/chutes-provider",
  "chutes-provider": "@openclaw/chutes-provider",
  "cloudflare-ai-gateway": "@openclaw/cloudflare-ai-gateway-provider",
  "cloudflare-ai-gateway-provider": "@openclaw/cloudflare-ai-gateway-provider",
  codex: "@openclaw/codex",
  comfy: "@openclaw/comfy-provider",
  "comfy-provider": "@openclaw/comfy-provider",
  "copilot-proxy": "@openclaw/copilot-proxy",
  deepgram: "@openclaw/deepgram-provider",
  "deepgram-provider": "@openclaw/deepgram-provider",
  deepinfra: "@openclaw/deepinfra-provider",
  "deepinfra-provider": "@openclaw/deepinfra-provider",
  deepseek: "@openclaw/deepseek-provider",
  "deepseek-provider": "@openclaw/deepseek-provider",
  "device-pair": "@openclaw/device-pair",
  "diagnostics-otel": "@openclaw/diagnostics-otel",
  "diagnostics-prometheus": "@openclaw/diagnostics-prometheus",
  diffs: "@openclaw/diffs",
  "diffs-language-pack": "@openclaw/diffs-language-pack",
  discord: "@openclaw/discord",
  "document-extract": "@openclaw/document-extract-plugin",
  "document-extract-plugin": "@openclaw/document-extract-plugin",
  duckduckgo: "@openclaw/duckduckgo-plugin",
  "duckduckgo-plugin": "@openclaw/duckduckgo-plugin",
  elevenlabs: "@openclaw/elevenlabs-speech",
  "elevenlabs-speech": "@openclaw/elevenlabs-speech",
  exa: "@openclaw/exa-plugin",
  "exa-plugin": "@openclaw/exa-plugin",
  fal: "@openclaw/fal-provider",
  "fal-provider": "@openclaw/fal-provider",
  feishu: "@openclaw/feishu",
  "file-transfer": "@openclaw/file-transfer",
  firecrawl: "@openclaw/firecrawl-plugin",
  "firecrawl-plugin": "@openclaw/firecrawl-plugin",
  fireworks: "@openclaw/fireworks-provider",
  "fireworks-provider": "@openclaw/fireworks-provider",
  "github-copilot": "@openclaw/github-copilot-provider",
  "github-copilot-provider": "@openclaw/github-copilot-provider",
  google: "@openclaw/google-plugin",
  "google-meet": "@openclaw/google-meet",
  "google-plugin": "@openclaw/google-plugin",
  googlechat: "@openclaw/googlechat",
  gradium: "@openclaw/gradium-speech",
  "gradium-speech": "@openclaw/gradium-speech",
  groq: "@openclaw/groq-provider",
  "groq-provider": "@openclaw/groq-provider",
  huggingface: "@openclaw/huggingface-provider",
  "huggingface-provider": "@openclaw/huggingface-provider",
  imessage: "@openclaw/imessage",
  inworld: "@openclaw/inworld-speech",
  "inworld-speech": "@openclaw/inworld-speech",
  irc: "@openclaw/irc",
  kilocode: "@openclaw/kilocode-provider",
  "kilocode-provider": "@openclaw/kilocode-provider",
  kimi: "@openclaw/kimi-provider",
  "kimi-coding": "@openclaw/kimi-provider",
  "kimi-provider": "@openclaw/kimi-provider",
  line: "@openclaw/line",
  litellm: "@openclaw/litellm-provider",
  "litellm-provider": "@openclaw/litellm-provider",
  "llm-task": "@openclaw/llm-task",
  lmstudio: "@openclaw/lmstudio-provider",
  "lmstudio-provider": "@openclaw/lmstudio-provider",
  lobster: "@openclaw/lobster",
  matrix: "@openclaw/matrix",
  mattermost: "@openclaw/mattermost",
  "memory-core": "@openclaw/memory-core",
  "memory-lancedb": "@openclaw/memory-lancedb",
  "memory-wiki": "@openclaw/memory-wiki",
  microsoft: "@openclaw/microsoft-speech",
  "microsoft-foundry": "@openclaw/microsoft-foundry",
  "microsoft-speech": "@openclaw/microsoft-speech",
  "migrate-claude": "@openclaw/migrate-claude",
  "migrate-hermes": "@openclaw/migrate-hermes",
  minimax: "@openclaw/minimax-provider",
  "minimax-provider": "@openclaw/minimax-provider",
  mistral: "@openclaw/mistral-provider",
  "mistral-provider": "@openclaw/mistral-provider",
  moonshot: "@openclaw/moonshot-provider",
  "moonshot-provider": "@openclaw/moonshot-provider",
  msteams: "@openclaw/msteams",
  "nextcloud-talk": "@openclaw/nextcloud-talk",
  nostr: "@openclaw/nostr",
  nvidia: "@openclaw/nvidia-provider",
  "nvidia-provider": "@openclaw/nvidia-provider",
  ollama: "@openclaw/ollama-provider",
  "ollama-provider": "@openclaw/ollama-provider",
  "open-prose": "@openclaw/open-prose",
  openai: "@openclaw/openai-provider",
  "openai-provider": "@openclaw/openai-provider",
  opencode: "@openclaw/opencode-provider",
  "opencode-go": "@openclaw/opencode-go-provider",
  "opencode-go-provider": "@openclaw/opencode-go-provider",
  "opencode-provider": "@openclaw/opencode-provider",
  openrouter: "@openclaw/openrouter-provider",
  "openrouter-provider": "@openclaw/openrouter-provider",
  openshell: "@openclaw/openshell-sandbox",
  "openshell-sandbox": "@openclaw/openshell-sandbox",
  perplexity: "@openclaw/perplexity-plugin",
  "perplexity-plugin": "@openclaw/perplexity-plugin",
  "phone-control": "@openclaw/phone-control",
  "qa-channel": "@openclaw/qa-channel",
  "qa-lab": "@openclaw/qa-lab",
  "qa-matrix": "@openclaw/qa-matrix",
  qianfan: "@openclaw/qianfan-provider",
  "qianfan-provider": "@openclaw/qianfan-provider",
  qqbot: "@openclaw/qqbot",
  qwen: "@openclaw/qwen-provider",
  "qwen-provider": "@openclaw/qwen-provider",
  runway: "@openclaw/runway-provider",
  "runway-provider": "@openclaw/runway-provider",
  searxng: "@openclaw/searxng-plugin",
  "searxng-plugin": "@openclaw/searxng-plugin",
  senseaudio: "@openclaw/senseaudio-provider",
  "senseaudio-provider": "@openclaw/senseaudio-provider",
  sglang: "@openclaw/sglang-provider",
  "sglang-provider": "@openclaw/sglang-provider",
  signal: "@openclaw/signal",
  "skill-workshop": "@openclaw/skill-workshop",
  slack: "@openclaw/slack",
  stepfun: "@openclaw/stepfun-provider",
  "stepfun-provider": "@openclaw/stepfun-provider",
  "synology-chat": "@openclaw/synology-chat",
  synthetic: "@openclaw/synthetic-provider",
  "synthetic-provider": "@openclaw/synthetic-provider",
  "talk-voice": "@openclaw/talk-voice",
  tavily: "@openclaw/tavily-plugin",
  "tavily-plugin": "@openclaw/tavily-plugin",
  telegram: "@openclaw/telegram",
  tencent: "@openclaw/tencent-provider",
  "tencent-provider": "@openclaw/tencent-provider",
  "thread-ownership": "@openclaw/thread-ownership",
  tlon: "@openclaw/tlon",
  together: "@openclaw/together-provider",
  "together-provider": "@openclaw/together-provider",
  tokenjuice: "@openclaw/tokenjuice",
  "tts-local-cli": "@openclaw/tts-local-cli",
  twitch: "@openclaw/twitch",
  venice: "@openclaw/venice-provider",
  "venice-provider": "@openclaw/venice-provider",
  "vercel-ai-gateway": "@openclaw/vercel-ai-gateway-provider",
  "vercel-ai-gateway-provider": "@openclaw/vercel-ai-gateway-provider",
  vllm: "@openclaw/vllm-provider",
  "vllm-provider": "@openclaw/vllm-provider",
  "voice-call": "@openclaw/voice-call",
  volcengine: "@openclaw/volcengine-provider",
  "volcengine-provider": "@openclaw/volcengine-provider",
  voyage: "@openclaw/voyage-provider",
  "voyage-provider": "@openclaw/voyage-provider",
  vydra: "@openclaw/vydra-provider",
  "vydra-provider": "@openclaw/vydra-provider",
  "web-readability": "@openclaw/web-readability-plugin",
  "web-readability-plugin": "@openclaw/web-readability-plugin",
  webhooks: "@openclaw/webhooks",
  whatsapp: "@openclaw/whatsapp",
  xai: "@openclaw/xai-plugin",
  "xai-plugin": "@openclaw/xai-plugin",
  xiaomi: "@openclaw/xiaomi-provider",
  "xiaomi-provider": "@openclaw/xiaomi-provider",
  zai: "@openclaw/zai-provider",
  "zai-provider": "@openclaw/zai-provider",
  zalo: "@openclaw/zalo",
  zalouser: "@openclaw/zalouser",
} as const;

export function getOpenClawExtensionPackageName(slug: string): string | null {
  const normalizedSlug = slug.trim().toLowerCase();
  if (!normalizedSlug) return null;

  return (
    OPENCLAW_EXTENSION_SLUG_TO_PACKAGE[
      normalizedSlug as keyof typeof OPENCLAW_EXTENSION_SLUG_TO_PACKAGE
    ] ?? null
  );
}

export function getOpenClawPackageCandidateNames(requestedName: string): string[] {
  if (requestedName.includes("/")) return [requestedName];

  const officialPackageName = getOpenClawExtensionPackageName(requestedName);
  return Array.from(
    new Set(
      [officialPackageName, `@openclaw/${requestedName}`, requestedName].filter(
        (name): name is string => typeof name === "string" && name.length > 0,
      ),
    ),
  );
}
