/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublishSkillRouteImport } from './routes/publish-skill'
import { Route as PublishPluginRouteImport } from './routes/publish-plugin'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountBannedRouteImport } from './routes/account-banned'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SoulsIndexRouteImport } from './routes/souls/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as PublishersIndexRouteImport } from './routes/publishers/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as UserHandleRouteImport } from './routes/user/$handle'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as SoulsSlugRouteImport } from './routes/souls/$slug'
import { Route as SkillsPublishRouteImport } from './routes/skills/publish'
import { Route as PluginsPublishRouteImport } from './routes/plugins/publish'
import { Route as PluginsNewRouteImport } from './routes/plugins/new'
import { Route as PluginsNameRouteImport } from './routes/plugins/$name'
import { Route as PackagesNewRouteImport } from './routes/packages/new'
import { Route as PackagesNameRouteImport } from './routes/packages/$name'
import { Route as PHandleRouteImport } from './routes/p/$handle'
import { Route as OrgsHandleRouteImport } from './routes/orgs/$handle'
import { Route as DocsAuthRouteImport } from './routes/docs/auth'
import { Route as CliDeviceRouteImport } from './routes/cli/device'
import { Route as CliAuthRouteImport } from './routes/cli/auth'
import { Route as OwnerSlugRouteImport } from './routes/$owner/$slug'
import { Route as PluginsScopeNameRouteImport } from './routes/plugins/$scope/$name'
import { Route as PluginsNameSecurityAuditRouteImport } from './routes/plugins/$name/security-audit'
import { Route as PackagesScopeNameRouteImport } from './routes/packages/$scope/$name'
import { Route as OwnerSlugSettingsRouteImport } from './routes/$owner/$slug/settings'
import { Route as OwnerSlugSecurityAuditRouteImport } from './routes/$owner/$slug/security-audit'
import { Route as PluginsScopeNameSecurityAuditRouteImport } from './routes/plugins/$scope/$name/security-audit'
import { Route as PluginsNameSecurityScannerRouteImport } from './routes/plugins/$name/security/$scanner'
import { Route as OwnerSlugSecurityScannerRouteImport } from './routes/$owner/$slug/security/$scanner'
import { Route as PluginsScopeNameSecurityScannerRouteImport } from './routes/plugins/$scope/$name/security/$scanner'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishSkillRoute = PublishSkillRouteImport.update({
  id: '/publish-skill',
  path: '/publish-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishPluginRoute = PublishPluginRouteImport.update({
  id: '/publish-plugin',
  path: '/publish-plugin',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBannedRoute = AccountBannedRouteImport.update({
  id: '/account-banned',
  path: '/account-banned',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsIndexRoute = SoulsIndexRouteImport.update({
  id: '/souls/',
  path: '/souls/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishersIndexRoute = PublishersIndexRouteImport.update({
  id: '/publishers/',
  path: '/publishers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHandleRoute = UserHandleRouteImport.update({
  id: '/user/$handle',
  path: '/user/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsSlugRoute = SoulsSlugRouteImport.update({
  id: '/souls/$slug',
  path: '/souls/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsPublishRoute = SkillsPublishRouteImport.update({
  id: '/skills/publish',
  path: '/skills/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPublishRoute = PluginsPublishRouteImport.update({
  id: '/plugins/publish',
  path: '/plugins/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsNewRoute = PluginsNewRouteImport.update({
  id: '/plugins/new',
  path: '/plugins/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsNameRoute = PluginsNameRouteImport.update({
  id: '/plugins/$name',
  path: '/plugins/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesNewRoute = PackagesNewRouteImport.update({
  id: '/packages/new',
  path: '/packages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesNameRoute = PackagesNameRouteImport.update({
  id: '/packages/$name',
  path: '/packages/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsHandleRoute = OrgsHandleRouteImport.update({
  id: '/orgs/$handle',
  path: '/orgs/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAuthRoute = DocsAuthRouteImport.update({
  id: '/docs/auth',
  path: '/docs/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CliDeviceRoute = CliDeviceRouteImport.update({
  id: '/cli/device',
  path: '/cli/device',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSlugRoute = OwnerSlugRouteImport.update({
  id: '/$owner/$slug',
  path: '/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsScopeNameRoute = PluginsScopeNameRouteImport.update({
  id: '/plugins/$scope/$name',
  path: '/plugins/$scope/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsNameSecurityAuditRoute =
  PluginsNameSecurityAuditRouteImport.update({
    id: '/security-audit',
    path: '/security-audit',
    getParentRoute: () => PluginsNameRoute,
  } as any)
const PackagesScopeNameRoute = PackagesScopeNameRouteImport.update({
  id: '/packages/$scope/$name',
  path: '/packages/$scope/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSlugSettingsRoute = OwnerSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerSlugRoute,
} as any)
const OwnerSlugSecurityAuditRoute = OwnerSlugSecurityAuditRouteImport.update({
  id: '/security-audit',
  path: '/security-audit',
  getParentRoute: () => OwnerSlugRoute,
} as any)
const PluginsScopeNameSecurityAuditRoute =
  PluginsScopeNameSecurityAuditRouteImport.update({
    id: '/security-audit',
    path: '/security-audit',
    getParentRoute: () => PluginsScopeNameRoute,
  } as any)
const PluginsNameSecurityScannerRoute =
  PluginsNameSecurityScannerRouteImport.update({
    id: '/security/$scanner',
    path: '/security/$scanner',
    getParentRoute: () => PluginsNameRoute,
  } as any)
const OwnerSlugSecurityScannerRoute =
  OwnerSlugSecurityScannerRouteImport.update({
    id: '/security/$scanner',
    path: '/security/$scanner',
    getParentRoute: () => OwnerSlugRoute,
  } as any)
const PluginsScopeNameSecurityScannerRoute =
  PluginsScopeNameSecurityScannerRouteImport.update({
    id: '/security/$scanner',
    path: '/security/$scanner',
    getParentRoute: () => PluginsScopeNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account-banned': typeof AccountBannedRoute
  '/admin': typeof AdminRoute
  '/audits': typeof AuditsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/management': typeof ManagementRoute
  '/publish-plugin': typeof PublishPluginRoute
  '/publish-skill': typeof PublishSkillRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRouteWithChildren
  '/cli/auth': typeof CliAuthRoute
  '/cli/device': typeof CliDeviceRoute
  '/docs/auth': typeof DocsAuthRoute
  '/orgs/$handle': typeof OrgsHandleRoute
  '/p/$handle': typeof PHandleRoute
  '/packages/$name': typeof PackagesNameRoute
  '/packages/new': typeof PackagesNewRoute
  '/plugins/$name': typeof PluginsNameRouteWithChildren
  '/plugins/new': typeof PluginsNewRoute
  '/plugins/publish': typeof PluginsPublishRoute
  '/skills/publish': typeof SkillsPublishRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/user/$handle': typeof UserHandleRoute
  '/packages/': typeof PackagesIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/souls/': typeof SoulsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$owner/$slug/security-audit': typeof OwnerSlugSecurityAuditRoute
  '/$owner/$slug/settings': typeof OwnerSlugSettingsRoute
  '/packages/$scope/$name': typeof PackagesScopeNameRoute
  '/plugins/$name/security-audit': typeof PluginsNameSecurityAuditRoute
  '/plugins/$scope/$name': typeof PluginsScopeNameRouteWithChildren
  '/$owner/$slug/security/$scanner': typeof OwnerSlugSecurityScannerRoute
  '/plugins/$name/security/$scanner': typeof PluginsNameSecurityScannerRoute
  '/plugins/$scope/$name/security-audit': typeof PluginsScopeNameSecurityAuditRoute
  '/plugins/$scope/$name/security/$scanner': typeof PluginsScopeNameSecurityScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account-banned': typeof AccountBannedRoute
  '/admin': typeof AdminRoute
  '/audits': typeof AuditsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/management': typeof ManagementRoute
  '/publish-plugin': typeof PublishPluginRoute
  '/publish-skill': typeof PublishSkillRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRouteWithChildren
  '/cli/auth': typeof CliAuthRoute
  '/cli/device': typeof CliDeviceRoute
  '/docs/auth': typeof DocsAuthRoute
  '/orgs/$handle': typeof OrgsHandleRoute
  '/p/$handle': typeof PHandleRoute
  '/packages/$name': typeof PackagesNameRoute
  '/packages/new': typeof PackagesNewRoute
  '/plugins/$name': typeof PluginsNameRouteWithChildren
  '/plugins/new': typeof PluginsNewRoute
  '/plugins/publish': typeof PluginsPublishRoute
  '/skills/publish': typeof SkillsPublishRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/user/$handle': typeof UserHandleRoute
  '/packages': typeof PackagesIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/publishers': typeof PublishersIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/souls': typeof SoulsIndexRoute
  '/users': typeof UsersIndexRoute
  '/$owner/$slug/security-audit': typeof OwnerSlugSecurityAuditRoute
  '/$owner/$slug/settings': typeof OwnerSlugSettingsRoute
  '/packages/$scope/$name': typeof PackagesScopeNameRoute
  '/plugins/$name/security-audit': typeof PluginsNameSecurityAuditRoute
  '/plugins/$scope/$name': typeof PluginsScopeNameRouteWithChildren
  '/$owner/$slug/security/$scanner': typeof OwnerSlugSecurityScannerRoute
  '/plugins/$name/security/$scanner': typeof PluginsNameSecurityScannerRoute
  '/plugins/$scope/$name/security-audit': typeof PluginsScopeNameSecurityAuditRoute
  '/plugins/$scope/$name/security/$scanner': typeof PluginsScopeNameSecurityScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/account-banned': typeof AccountBannedRoute
  '/admin': typeof AdminRoute
  '/audits': typeof AuditsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/management': typeof ManagementRoute
  '/publish-plugin': typeof PublishPluginRoute
  '/publish-skill': typeof PublishSkillRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRouteWithChildren
  '/cli/auth': typeof CliAuthRoute
  '/cli/device': typeof CliDeviceRoute
  '/docs/auth': typeof DocsAuthRoute
  '/orgs/$handle': typeof OrgsHandleRoute
  '/p/$handle': typeof PHandleRoute
  '/packages/$name': typeof PackagesNameRoute
  '/packages/new': typeof PackagesNewRoute
  '/plugins/$name': typeof PluginsNameRouteWithChildren
  '/plugins/new': typeof PluginsNewRoute
  '/plugins/publish': typeof PluginsPublishRoute
  '/skills/publish': typeof SkillsPublishRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/user/$handle': typeof UserHandleRoute
  '/packages/': typeof PackagesIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/publishers/': typeof PublishersIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/souls/': typeof SoulsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/$owner/$slug/security-audit': typeof OwnerSlugSecurityAuditRoute
  '/$owner/$slug/settings': typeof OwnerSlugSettingsRoute
  '/packages/$scope/$name': typeof PackagesScopeNameRoute
  '/plugins/$name/security-audit': typeof PluginsNameSecurityAuditRoute
  '/plugins/$scope/$name': typeof PluginsScopeNameRouteWithChildren
  '/$owner/$slug/security/$scanner': typeof OwnerSlugSecurityScannerRoute
  '/plugins/$name/security/$scanner': typeof PluginsNameSecurityScannerRoute
  '/plugins/$scope/$name/security-audit': typeof PluginsScopeNameSecurityAuditRoute
  '/plugins/$scope/$name/security/$scanner': typeof PluginsScopeNameSecurityScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/account-banned'
    | '/admin'
    | '/audits'
    | '/dashboard'
    | '/import'
    | '/management'
    | '/publish-plugin'
    | '/publish-skill'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/cli/auth'
    | '/cli/device'
    | '/docs/auth'
    | '/orgs/$handle'
    | '/p/$handle'
    | '/packages/$name'
    | '/packages/new'
    | '/plugins/$name'
    | '/plugins/new'
    | '/plugins/publish'
    | '/skills/publish'
    | '/souls/$slug'
    | '/u/$handle'
    | '/user/$handle'
    | '/packages/'
    | '/plugins/'
    | '/publishers/'
    | '/skills/'
    | '/souls/'
    | '/users/'
    | '/$owner/$slug/security-audit'
    | '/$owner/$slug/settings'
    | '/packages/$scope/$name'
    | '/plugins/$name/security-audit'
    | '/plugins/$scope/$name'
    | '/$owner/$slug/security/$scanner'
    | '/plugins/$name/security/$scanner'
    | '/plugins/$scope/$name/security-audit'
    | '/plugins/$scope/$name/security/$scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/account-banned'
    | '/admin'
    | '/audits'
    | '/dashboard'
    | '/import'
    | '/management'
    | '/publish-plugin'
    | '/publish-skill'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/cli/auth'
    | '/cli/device'
    | '/docs/auth'
    | '/orgs/$handle'
    | '/p/$handle'
    | '/packages/$name'
    | '/packages/new'
    | '/plugins/$name'
    | '/plugins/new'
    | '/plugins/publish'
    | '/skills/publish'
    | '/souls/$slug'
    | '/u/$handle'
    | '/user/$handle'
    | '/packages'
    | '/plugins'
    | '/publishers'
    | '/skills'
    | '/souls'
    | '/users'
    | '/$owner/$slug/security-audit'
    | '/$owner/$slug/settings'
    | '/packages/$scope/$name'
    | '/plugins/$name/security-audit'
    | '/plugins/$scope/$name'
    | '/$owner/$slug/security/$scanner'
    | '/plugins/$name/security/$scanner'
    | '/plugins/$scope/$name/security-audit'
    | '/plugins/$scope/$name/security/$scanner'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/account-banned'
    | '/admin'
    | '/audits'
    | '/dashboard'
    | '/import'
    | '/management'
    | '/publish-plugin'
    | '/publish-skill'
    | '/search'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/cli/auth'
    | '/cli/device'
    | '/docs/auth'
    | '/orgs/$handle'
    | '/p/$handle'
    | '/packages/$name'
    | '/packages/new'
    | '/plugins/$name'
    | '/plugins/new'
    | '/plugins/publish'
    | '/skills/publish'
    | '/souls/$slug'
    | '/u/$handle'
    | '/user/$handle'
    | '/packages/'
    | '/plugins/'
    | '/publishers/'
    | '/skills/'
    | '/souls/'
    | '/users/'
    | '/$owner/$slug/security-audit'
    | '/$owner/$slug/settings'
    | '/packages/$scope/$name'
    | '/plugins/$name/security-audit'
    | '/plugins/$scope/$name'
    | '/$owner/$slug/security/$scanner'
    | '/plugins/$name/security/$scanner'
    | '/plugins/$scope/$name/security-audit'
    | '/plugins/$scope/$name/security/$scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AccountBannedRoute: typeof AccountBannedRoute
  AdminRoute: typeof AdminRoute
  AuditsRoute: typeof AuditsRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  ManagementRoute: typeof ManagementRoute
  PublishPluginRoute: typeof PublishPluginRoute
  PublishSkillRoute: typeof PublishSkillRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StarsRoute: typeof StarsRoute
  UploadRoute: typeof UploadRoute
  OwnerSlugRoute: typeof OwnerSlugRouteWithChildren
  CliAuthRoute: typeof CliAuthRoute
  CliDeviceRoute: typeof CliDeviceRoute
  DocsAuthRoute: typeof DocsAuthRoute
  OrgsHandleRoute: typeof OrgsHandleRoute
  PHandleRoute: typeof PHandleRoute
  PackagesNameRoute: typeof PackagesNameRoute
  PackagesNewRoute: typeof PackagesNewRoute
  PluginsNameRoute: typeof PluginsNameRouteWithChildren
  PluginsNewRoute: typeof PluginsNewRoute
  PluginsPublishRoute: typeof PluginsPublishRoute
  SkillsPublishRoute: typeof SkillsPublishRoute
  SoulsSlugRoute: typeof SoulsSlugRoute
  UHandleRoute: typeof UHandleRoute
  UserHandleRoute: typeof UserHandleRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PublishersIndexRoute: typeof PublishersIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SoulsIndexRoute: typeof SoulsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PackagesScopeNameRoute: typeof PackagesScopeNameRoute
  PluginsScopeNameRoute: typeof PluginsScopeNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-skill': {
      id: '/publish-skill'
      path: '/publish-skill'
      fullPath: '/publish-skill'
      preLoaderRoute: typeof PublishSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-plugin': {
      id: '/publish-plugin'
      path: '/publish-plugin'
      fullPath: '/publish-plugin'
      preLoaderRoute: typeof PublishPluginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-banned': {
      id: '/account-banned'
      path: '/account-banned'
      fullPath: '/account-banned'
      preLoaderRoute: typeof AccountBannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/': {
      id: '/souls/'
      path: '/souls'
      fullPath: '/souls/'
      preLoaderRoute: typeof SoulsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishers/': {
      id: '/publishers/'
      path: '/publishers'
      fullPath: '/publishers/'
      preLoaderRoute: typeof PublishersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$handle': {
      id: '/user/$handle'
      path: '/user/$handle'
      fullPath: '/user/$handle'
      preLoaderRoute: typeof UserHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/$slug': {
      id: '/souls/$slug'
      path: '/souls/$slug'
      fullPath: '/souls/$slug'
      preLoaderRoute: typeof SoulsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/publish': {
      id: '/skills/publish'
      path: '/skills/publish'
      fullPath: '/skills/publish'
      preLoaderRoute: typeof SkillsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/publish': {
      id: '/plugins/publish'
      path: '/plugins/publish'
      fullPath: '/plugins/publish'
      preLoaderRoute: typeof PluginsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/new': {
      id: '/plugins/new'
      path: '/plugins/new'
      fullPath: '/plugins/new'
      preLoaderRoute: typeof PluginsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$name': {
      id: '/plugins/$name'
      path: '/plugins/$name'
      fullPath: '/plugins/$name'
      preLoaderRoute: typeof PluginsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/new': {
      id: '/packages/new'
      path: '/packages/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof PackagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$name': {
      id: '/packages/$name'
      path: '/packages/$name'
      fullPath: '/packages/$name'
      preLoaderRoute: typeof PackagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$handle': {
      id: '/orgs/$handle'
      path: '/orgs/$handle'
      fullPath: '/orgs/$handle'
      preLoaderRoute: typeof OrgsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/auth': {
      id: '/docs/auth'
      path: '/docs/auth'
      fullPath: '/docs/auth'
      preLoaderRoute: typeof DocsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/device': {
      id: '/cli/device'
      path: '/cli/device'
      fullPath: '/cli/device'
      preLoaderRoute: typeof CliDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$slug': {
      id: '/$owner/$slug'
      path: '/$owner/$slug'
      fullPath: '/$owner/$slug'
      preLoaderRoute: typeof OwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$scope/$name': {
      id: '/plugins/$scope/$name'
      path: '/plugins/$scope/$name'
      fullPath: '/plugins/$scope/$name'
      preLoaderRoute: typeof PluginsScopeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$name/security-audit': {
      id: '/plugins/$name/security-audit'
      path: '/security-audit'
      fullPath: '/plugins/$name/security-audit'
      preLoaderRoute: typeof PluginsNameSecurityAuditRouteImport
      parentRoute: typeof PluginsNameRoute
    }
    '/packages/$scope/$name': {
      id: '/packages/$scope/$name'
      path: '/packages/$scope/$name'
      fullPath: '/packages/$scope/$name'
      preLoaderRoute: typeof PackagesScopeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$slug/settings': {
      id: '/$owner/$slug/settings'
      path: '/settings'
      fullPath: '/$owner/$slug/settings'
      preLoaderRoute: typeof OwnerSlugSettingsRouteImport
      parentRoute: typeof OwnerSlugRoute
    }
    '/$owner/$slug/security-audit': {
      id: '/$owner/$slug/security-audit'
      path: '/security-audit'
      fullPath: '/$owner/$slug/security-audit'
      preLoaderRoute: typeof OwnerSlugSecurityAuditRouteImport
      parentRoute: typeof OwnerSlugRoute
    }
    '/plugins/$scope/$name/security-audit': {
      id: '/plugins/$scope/$name/security-audit'
      path: '/security-audit'
      fullPath: '/plugins/$scope/$name/security-audit'
      preLoaderRoute: typeof PluginsScopeNameSecurityAuditRouteImport
      parentRoute: typeof PluginsScopeNameRoute
    }
    '/plugins/$name/security/$scanner': {
      id: '/plugins/$name/security/$scanner'
      path: '/security/$scanner'
      fullPath: '/plugins/$name/security/$scanner'
      preLoaderRoute: typeof PluginsNameSecurityScannerRouteImport
      parentRoute: typeof PluginsNameRoute
    }
    '/$owner/$slug/security/$scanner': {
      id: '/$owner/$slug/security/$scanner'
      path: '/security/$scanner'
      fullPath: '/$owner/$slug/security/$scanner'
      preLoaderRoute: typeof OwnerSlugSecurityScannerRouteImport
      parentRoute: typeof OwnerSlugRoute
    }
    '/plugins/$scope/$name/security/$scanner': {
      id: '/plugins/$scope/$name/security/$scanner'
      path: '/security/$scanner'
      fullPath: '/plugins/$scope/$name/security/$scanner'
      preLoaderRoute: typeof PluginsScopeNameSecurityScannerRouteImport
      parentRoute: typeof PluginsScopeNameRoute
    }
  }
}

interface OwnerSlugRouteChildren {
  OwnerSlugSecurityAuditRoute: typeof OwnerSlugSecurityAuditRoute
  OwnerSlugSettingsRoute: typeof OwnerSlugSettingsRoute
  OwnerSlugSecurityScannerRoute: typeof OwnerSlugSecurityScannerRoute
}

const OwnerSlugRouteChildren: OwnerSlugRouteChildren = {
  OwnerSlugSecurityAuditRoute: OwnerSlugSecurityAuditRoute,
  OwnerSlugSettingsRoute: OwnerSlugSettingsRoute,
  OwnerSlugSecurityScannerRoute: OwnerSlugSecurityScannerRoute,
}

const OwnerSlugRouteWithChildren = OwnerSlugRoute._addFileChildren(
  OwnerSlugRouteChildren,
)

interface PluginsNameRouteChildren {
  PluginsNameSecurityAuditRoute: typeof PluginsNameSecurityAuditRoute
  PluginsNameSecurityScannerRoute: typeof PluginsNameSecurityScannerRoute
}

const PluginsNameRouteChildren: PluginsNameRouteChildren = {
  PluginsNameSecurityAuditRoute: PluginsNameSecurityAuditRoute,
  PluginsNameSecurityScannerRoute: PluginsNameSecurityScannerRoute,
}

const PluginsNameRouteWithChildren = PluginsNameRoute._addFileChildren(
  PluginsNameRouteChildren,
)

interface PluginsScopeNameRouteChildren {
  PluginsScopeNameSecurityAuditRoute: typeof PluginsScopeNameSecurityAuditRoute
  PluginsScopeNameSecurityScannerRoute: typeof PluginsScopeNameSecurityScannerRoute
}

const PluginsScopeNameRouteChildren: PluginsScopeNameRouteChildren = {
  PluginsScopeNameSecurityAuditRoute: PluginsScopeNameSecurityAuditRoute,
  PluginsScopeNameSecurityScannerRoute: PluginsScopeNameSecurityScannerRoute,
}

const PluginsScopeNameRouteWithChildren =
  PluginsScopeNameRoute._addFileChildren(PluginsScopeNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AccountBannedRoute: AccountBannedRoute,
  AdminRoute: AdminRoute,
  AuditsRoute: AuditsRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  ManagementRoute: ManagementRoute,
  PublishPluginRoute: PublishPluginRoute,
  PublishSkillRoute: PublishSkillRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StarsRoute: StarsRoute,
  UploadRoute: UploadRoute,
  OwnerSlugRoute: OwnerSlugRouteWithChildren,
  CliAuthRoute: CliAuthRoute,
  CliDeviceRoute: CliDeviceRoute,
  DocsAuthRoute: DocsAuthRoute,
  OrgsHandleRoute: OrgsHandleRoute,
  PHandleRoute: PHandleRoute,
  PackagesNameRoute: PackagesNameRoute,
  PackagesNewRoute: PackagesNewRoute,
  PluginsNameRoute: PluginsNameRouteWithChildren,
  PluginsNewRoute: PluginsNewRoute,
  PluginsPublishRoute: PluginsPublishRoute,
  SkillsPublishRoute: SkillsPublishRoute,
  SoulsSlugRoute: SoulsSlugRoute,
  UHandleRoute: UHandleRoute,
  UserHandleRoute: UserHandleRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PublishersIndexRoute: PublishersIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SoulsIndexRoute: SoulsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PackagesScopeNameRoute: PackagesScopeNameRoute,
  PluginsScopeNameRoute: PluginsScopeNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
